# Generated by Django 4.2.4 on 2023-08-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('social_media', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('latest_post_date', models.DateField(blank=True, null=True)),
                ('account_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('account_reached', models.BigIntegerField(blank=True, null=True)),
                ('engagement', models.BigIntegerField(blank=True, null=True)),
                ('views', models.BigIntegerField(blank=True, null=True)),
                ('profile_visited', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
