# Generated by Django 4.2.4 on 2023-08-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='profile_summary',
            field=models.TextField(default=''),
        ),
    ]
