# Generated by Django 4.2.4 on 2023-08-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialmedia_profile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('type_of_event', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=512, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_transaction', models.TimeField(blank=True, null=True)),
                ('previous_report', models.CharField(blank=True, max_length=255, null=True)),
                ('block_height', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_blockchain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='risk',
            field=models.CharField(default='High', max_length=255),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('coin', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('notify', models.CharField(blank=True, max_length=255, null=True)),
                ('email_template', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.transaction')),
            ],
        ),
    ]
