# Generated by Django 4.2.4 on 2023-08-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_socialmedia_risk_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
