# Generated by Django 4.2.4 on 2023-08-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='event',
            new_name='transaction',
        ),
    ]
