# Generated by Django 4.2.4 on 2023-08-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_watchlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaction', unique=True),
        ),
    ]
