# Generated by Django 4.2.4 on 2023-08-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
