# Generated by Django 4.2.4 on 2023-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_time_of_transaction_transaction_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallets',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='profile_summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
