# Generated by Django 4.2.4 on 2023-08-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction_wallets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mixed_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
