# Generated by Django 4.2.4 on 2023-08-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_mixed_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
