# Generated by Django 4.2.4 on 2023-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_transaction_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='scam_reports',
            field=models.URLField(blank=True, null=True),
        ),
    ]
