# Generated by Django 4.2.4 on 2023-08-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaction_scam_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='scam_reports',
            field=models.URLField(blank=True, null=True),
        ),
    ]
