# Generated by Django 4.2.4 on 2023-08-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_account_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
